"""Combine the standalone energy and TTFT baseline plots into a single
side-by-side figure for the report.

The two source PNGs were generated by the Experiment-3 notebook with their
own titles ("Energy per query (log scale)" and "TTFT per query (log scale)").
This script adaptively scales them to a common height, pastes them side by
side with a small gutter, and writes the combined image to disk. Titles are
preserved because they are baked into the source bitmaps.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

WORKSPACE = Path(__file__).resolve().parents[1]

LEFT_SRC = WORKSPACE / "new_exp3" / "exp3_baseline_energy.png"
RIGHT_SRC = WORKSPACE / "new_exp3" / "exp3_baseline_ttft.png"
OUT_PATH = WORKSPACE / "new_exp3" / "exp3_baseline_compare_sidebyside.png"

GUTTER_PX = 20
BG_COLOR = (255, 255, 255)


def load_resized(path: Path, target_height: int) -> Image.Image:
    """Open `path` and resize so its height matches `target_height`.

    Width is scaled proportionally with high-quality LANCZOS resampling.
    Returns an RGBA image so the paste step preserves any transparency.
    """
    img = Image.open(path).convert("RGBA")
    if img.height == target_height:
        return img
    new_width = int(round(img.width * target_height / img.height))
    return img.resize((new_width, target_height), Image.LANCZOS)


def main() -> None:
    if not LEFT_SRC.exists():
        raise FileNotFoundError(f"Missing source plot: {LEFT_SRC}")
    if not RIGHT_SRC.exists():
        raise FileNotFoundError(f"Missing source plot: {RIGHT_SRC}")

    left_raw = Image.open(LEFT_SRC)
    right_raw = Image.open(RIGHT_SRC)

    target_height = max(left_raw.height, right_raw.height)

    left = load_resized(LEFT_SRC, target_height)
    right = load_resized(RIGHT_SRC, target_height)

    canvas_width = left.width + GUTTER_PX + right.width
    canvas = Image.new("RGB", (canvas_width, target_height), BG_COLOR)

    canvas.paste(left.convert("RGB"), (0, 0))
    canvas.paste(right.convert("RGB"), (left.width + GUTTER_PX, 0))

    canvas.save(OUT_PATH, format="PNG", optimize=True)
    print(f"Wrote {OUT_PATH}")
    print(f"  left:  {left.width}x{left.height} (from {LEFT_SRC.name})")
    print(f"  right: {right.width}x{right.height} (from {RIGHT_SRC.name})")
    print(f"  canvas: {canvas.width}x{canvas.height}")


if __name__ == "__main__":
    main()
